export type Course = {id:string;title:string;provider:string;mark:string;category:string;description:string;duration:string;hours:number|null;level:string;price:string;free:boolean;code:boolean;skills:string[];url:string;art:string;label:string;outcome:string};
export const courses: Course[] = [
{id:"google",title:"Google AI Professional Certificate",provider:"Google",mark:"G",category:"AI at work",description:"Make AI part of your working day. Explore research, writing, data analysis and building your own tools.",duration:"Self-paced",hours:null,level:"Beginner",price:"Paid · see provider",free:false,code:false,skills:["Productivity","Prompting","Data analysis"],url:"https://grow.google/ai-professional/",art:"lime",label:"THE PRACTICAL START",outcome:"Practise workplace tasks through 20+ hands-on activities, from research and writing to creating useful apps."},
{id:"genai",title:"Generative AI for Everyone",provider:"DeepLearning.AI",mark:"dl",category:"AI foundations",description:"Understand what generative AI can do, where it falls short, and how to put it to work.",duration:"3 weeks · 1–2 hrs/week",hours:6,level:"Beginner",price:"See provider plans",free:false,code:false,skills:["Generative AI","AI literacy","Strategy"],url:"https://www.deeplearning.ai/courses/genai4e",art:"lavender",label:"SEE THE BIGGER PICTURE",outcome:"Identify tasks that generative AI can support and consider its impact on work and organisations."},
{id:"elements",title:"Elements of AI: Introduction to AI",provider:"University of Helsinki · MinnaLearn",mark:"H",category:"AI foundations",description:"A thoughtful introduction to AI, with real-world ideas and exercises. No programming required.",duration:"Self-paced",hours:null,level:"Beginner",price:"Free course",free:true,code:false,skills:["AI literacy","Machine learning","Critical thinking"],url:"https://course.elementsofai.com/en-lu/",art:"peach",label:"CURIOSITY STARTS HERE",outcome:"Build a foundation for understanding AI, its applications and its implications for society."},
{id:"everyone",title:"AI for Everyone",provider:"DeepLearning.AI",mark:"dl",category:"AI strategy",description:"Learn the language of AI and recognise opportunities to use it in your organisation.",duration:"6 hrs 54 min",hours:6.9,level:"Beginner",price:"Certificate with PRO",free:false,code:false,skills:["AI strategy","Leadership","AI literacy"],url:"https://www.deeplearning.ai/courses/ai-for-everyone",art:"blue",label:"LEAD WITH UNDERSTANDING",outcome:"Understand AI project workflows and frame realistic opportunities for organisational change."},
{id:"prompt",title:"ChatGPT Prompt Engineering for Developers",provider:"DeepLearning.AI · OpenAI",mark:"dl",category:"Build with AI",description:"Turn prompting principles into working applications, with hands-on coding examples.",duration:"1 hr 30 min",hours:1.5,level:"Beginner · basic Python",price:"See provider plans",free:false,code:true,skills:["Prompting","Python","App development"],url:"https://www.deeplearning.ai/courses/chatgpt-prompt-eng",art:"pink",label:"FROM PROMPT TO PROTOTYPE",outcome:"Practise using language-model APIs for summarising, transforming text and building a chatbot."},
{id:"building",title:"Building AI",provider:"University of Helsinki · MinnaLearn",mark:"H",category:"Build with AI",description:"Explore the methods behind AI and learn how to turn an idea into a practical AI problem.",duration:"Self-paced",hours:null,level:"Beginner to intermediate",price:"Free course · certificate extra",free:true,code:true,skills:["Machine learning","Algorithms","Problem solving"],url:"https://buildingai.elementsofai.com/",art:"mint",label:"GO ONE LEVEL DEEPER",outcome:"Explore AI methods with exercises at different difficulty levels. Python helps with intermediate and advanced exercises."}
];
export const pathways = {
"Public officer": {title:"Make everyday public service work better.",description:"A practical route from understanding AI to drafting clearer briefs and exploring data. No coding experience needed.",ids:["genai","google","everyone"],project:"Create a two-page briefing from public reports. Check every claim against its source, then present the findings in three slides."},
"Business owner": {title:"Bring AI into your business, thoughtfully.",description:"Understand the opportunities, try useful workflows, and choose where AI can make a meaningful difference.",ids:["everyone","google","genai"],project:"Map one repetitive workflow, prototype an AI-assisted version using sample data, and compare quality and time spent."},
"Career explorer": {title:"Build confidence for your next chapter.",description:"Start with the essentials and develop practical skills you can demonstrate in your next role.",ids:["elements","genai","google"],project:"Use public information to research an industry, create a short presentation, and document how you verified the AI output."},
"Developer": {title:"Turn your ideas into working AI tools.",description:"Connect prompting skills with a deeper understanding of AI methods, then build something useful.",ids:["genai","prompt","building"],project:"Prototype a document summariser with public sample documents. Add source references and test it on ambiguous inputs."}
};
